### ISSUE TITLE
confused about code

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G2#13]
in your jupyter notebook file you have:
`
masses = [2.0, 3.0, 4.0]
`
I am sort of confused why there are 3 masses. Could you explain the purpose of this? It seems like there are only 2 masses colliding.

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski I fixed the code, check my merge request.

**Comment by poojashresthacode** [comment]
I am also confused in the code. Is it because two masses collide and they didn't get detached and remain as one? And move forward as one single body? But then mass is 4 for the 3rd one. How?

**Comment by JustinJaniszewski** [comment]
I was thinking something like that but I believe the collision wouldn't be elastic then.

**Comment by JustinJaniszewski** [comment]
@Pranjal-Srivastava-2023 I just looked at your code and it looks much better. Nice job

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski Thanks! merge the request.
