### ISSUE TITLE
Group 4 work

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework3G2#18]
Group 4 has chosen the time of flight calculation for an object to project it horizontally.

**Comment by tirthbha** [comment]
We have switched our function to estimate kinetic energy and workdone.

**Comment by LinxuanHu** [comment]
we are working on 1d two body elastic collision

**Comment by tirthbha** [comment]
> we are working on 1d two body elastic collision

What is your argument function?

**Comment by LinxuanHu** [comment]
v1=(m1-m2)u1/(m1+m2)+(2m2u2)/(m1+m2)
v2=(m2-m1)u2/(m1+m2)+(2m1u1)/(m1+m2)
where v1, v2 are final velocity, m1, m2 are mass, u1, u2 are initial velocity

**Comment by tirthbha** [comment]
Using this argument, what will be the next function you are going to estimate?
