### ISSUE TITLE
confuse about the code and the kinetic energy

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework3G2#24]
i think we only need to consider two objects. Besides, for elastic collision, the kinetic energy should be the same before and after the collision. 
here are the equations for elastic collision
where v1, v2 are final velocity, m1, m2 are mass, u1, u2 are initial velocity
  v1=(m1-m2)*u1/(m1+m2)+(2*m2*u2)/(m1+m2)
  v2=(m2-m1)*u2/(m1+m2)+(2*m1*u1)/(m1+m2)

**Comment by Pranjal-Srivastava-2023** [comment]
@LinxuanHu Yes we have the working codes now in the repository.
