### ISSUE TITLE
error in elastic_collision.py. Mass 1 can equal zero.

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G2#25]
I ran your code with the mass of the first object being zero with it still returning a velocity value for the first object. 

https://github.com/ubsuny/23-Homework3G2/blob/5a5270719cccf0b6a2abd84170040407ced8864b/elastic_collision.py#L59C16-L59C16

**Comment by Pranjal-Srivastava-2023** [comment]
@JustinJaniszewski I think if the mass is 0 then there is no collision. m=0 is a physically wrong input. Besides, any object with 0 mass (such as photon) must travel at the speed of light, we can not assign m=0 any other velocity. The collision formula we used in the code works for massive objects only.

**Comment by Mosaddeq107** [comment]
> @JustinJaniszewski I think if the mass is 0 then there is no collision. m=0 is a physically wrong input. Besides, any object with 0 mass (such as photon) must travel at the speed of light, we can not assign m=0 any other velocity. The collision formula we used in the code works for massive objects only.

Yes. Nice explanation.
