### ISSUE TITLE
Periodic Time function

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G2#27]
Hi all,
 We have chosen time period of pendulum as the function for group 1.

**Comment by tirthbha** [comment]
What is your argument function and the next one?

**Comment by uarif** [comment]
I don't understand what you mean? @tirthbha

**Comment by uarif** [comment]
> Hi all, We have chosen time period of pendulum as the function for group 1.

thanx for letting the othejrs know,

**Comment by tirthbha** [comment]
> I don't understand what you mean? @tirthbha

We are going to implement a classical mechanics function  as a python function, right? And using that  function as an argument in another function.

**Comment by Mosaddeq107** [comment]
Is this issue resolved?

**Comment by Mosaddeq107** [comment]
I am closing this issue.
