### ISSUE TITLE
Filter use

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G2#31]
Can you guys explain that how to implement filter to the  classical function " find out the work done by a body moving with different velocities from point A to E (say)?

**Comment by uarif** [comment]
I don't know what does that mean, you can google it.

**Comment by Mosaddeq107** [comment]
HI @tirthbha 
You can try this code. I hope you will get an idea from the code below.

import math

def calculate_work(velocities, distances, force, angles):
    total_work = 0
    for i in range(len(velocities)):
        # Calculate work done in each segment using W = F * d * cos(theta)
        work_done = force * distances[i] * math.cos(math.radians(angles[i]))
        total_work += work_done
    return total_work

# Example data (velocities in m/s, distances in meters, force in Newtons, angles in degrees)
velocities = [10, 5, 8, 7, 6]  # Velocities at different segments
distances = [2, 3, 2, 4, 5]  # Distances covered in each segment
force = 20  # Constant force in Newtons
angles = [30, 45, 60, 90, 120]  # Angles between force and direction of motion in degrees

total_work_done = calculate_work(velocities, distances, force, angles)
print("Total work done:", total_work_done, "Joules")

**Comment by Mosaddeq107** [comment]
Did you get your answer?
