### ISSUE TITLE
Issue Creation

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework3G2#32]
How can I check the number of issues I have created?

**Comment by tirthbha** [comment]
Type involves:username in a box at the top of your page.

**Comment by uarif** [comment]
> How can I check the number of issues I have created?

You can also go to a specific group->issues->and then filter -> your issues. it will give you the number of your issues only.

**Comment by uarif** [comment]
For each group, you have to go to the specific group first @sharmistharanit

**Comment by uarif** [comment]
But @tirthbha is also correct. Thank you

**Comment by sharmistharanit** [comment]
Thank you for letting me know. It is really a piece of helpful information. @tirthbha @uarif
