### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G2#34]
How to separate the algorithm part in its own library (module) file?

**Comment by tirthbha** [comment]
Yes, I have the same question.

**Comment by tirthbha** [comment]
@reshnashrestha 
To separate the algorithm part into its own library (module) file in Python, you can follow these steps (as in our case: G4HW3)

Create a new Python file for your algorithm, let's call it work_calculator.py. This file will contain the calculate_work_done function.
Move the calculate_work_done function to work_calculator.py.
In your main code file, import the calculate_work_done function from work_calculator.py and use it as needed.
