### ISSUE TITLE
Code seems incomplete

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G2#35]
Hi all,
While I go through your file elastic_ciollision_h3_g2_mosaddeq.ipynb I find some lines are missing their last section.
<img width="803" alt="Image1" src="https://github.com/ubsuny/23-Homework3G2/assets/72980895/73d9b3c1-b7a6-4312-bc96-4d8d5ff09898">
 It might be the case that you uploaded the image instead of original file of code you executed. I suggest you to upload the original file so that there won't be anything missing.  I might be wrong, please correct me why it shows like that.

**Comment by tirthbha** [comment]
I think code is complete.

**Comment by LinxuanHu** [comment]
i have updated the code

**Comment by uarif** [comment]
yes, thanks for updating the code.

**Comment by reshnashrestha** [comment]
I noticed that as well.

**Comment by Mosaddeq107** [comment]
Thanks for notifying us....
