### ISSUE TITLE
We don't need to consider angle

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework3G2#40]
In the elastic_collision.py file, you have include a variable angle, since we are doing the one dimensional elastic collision, I don't think it is necessary to consider angle there.

**Comment by Pranjal-Srivastava-2023** [comment]
@LinxuanHu Yes, you are right. I will be removing those extra variables.

**Comment by Pranjal-Srivastava-2023** [comment]
@LinxuanHu Merge request sent.
