### ISSUE TITLE
Conversation made

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework3G2#43]
How will I check the number of conversations I have done with other groups?

**Comment by uarif** [comment]
If you click on the notification, on the left most side there is a button for "participation"

**Comment by uarif** [comment]
It shows your participation, but I guess it doesn't tell you about separate group participation.

**Comment by uarif** [comment]
You can google it and let us know too, thank you

**Comment by sharmistharanit** [comment]
Thank you so much. @uarif 

It was really helpful.

**Comment by Mosaddeq107** [comment]
I don't think you can count in by default like counting issues. But you can do it by using GitHub's API programmatically.

**Comment by sharmistharanit** [comment]
So I have to count them?
