### ISSUE TITLE
Unit_testing_confusion. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G2#46]
Hello, As, per my knowledge, the unit test is something, to check whether the code is correct or not, The unit test code, is a different code which checks the original code right?. To me more precise, should it be the same code and checking for different inputs, or it should be a different code?
Thank you,

**Comment by pratibha77118** [comment]
@uarif there are not any respond for this issue. I also want to be clear on this confusion.

**Comment by WildJimmy** [comment]
Answered this question here (https://github.com/ubsuny/23-Homework3G3/issues/55)

**Comment by Mosaddeq107** [comment]
Thank you for your suggestion
