### ISSUE TITLE
pycodestyle throws comment on your elastic_collison.py file

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G2#52]
Hi guys, just letting you know that I checked your code quality with pycodestyle, it is throwing some of the suggestions. Would you guys like to follow accordingly?
![image](https://github.com/ubsuny/23-Homework3G2/assets/144289804/ca92992b-ef20-4994-88c6-b7b0e0684973)

**Comment by Mosaddeq107** [comment]
Hi, @s4il3sh 
In which environment did you run this file?

**Comment by s4il3sh** [comment]
@Mosaddeq107 I used Jupyter Notebook
