### ISSUE TITLE
how to find how many conversations have i involved

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework3G2#53]
with my own group and with other group

**Comment by Mosaddeq107** [comment]
I don't think you can count in by default like counting issues. But you can do it by using GitHub's API programmatically.

**Comment by Mosaddeq107** [comment]
Or you can count it manually. @LinxuanHu

**Comment by Pranjal-Srivastava-2023** [comment]
Try typing the following in search bar "involves:Your_Username"

**Comment by pratibha77118** [comment]
Thanks. I do want to know the commits and conversations I did.
