### ISSUE TITLE
Higher-order corrections for Euler's method?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework3G2#79]
I am using Euler's method to solve uncoupled first-order ordinary homogenous and inhomogeneous differential equations. I used the first-order approximation out of habit and convenience. How can I determine if higher-order corrections are needed?

**Comment by WildJimmy** [comment]
Excellent question. I would compare the scale of the higher order corrections for the system you're solving and the precision you need. For example if your 2nd order correction is <1% of your first order approximation, there is likely no need for this

**Comment by AhmedCode99** [comment]
thanks
