### ISSUE TITLE
Label creation 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework3G2#8]
Hi @LinxuanHu 
We need to create at least 10 labels for our own project.

**Comment by LinxuanHu** [comment]
do you have any suggestion for the labels

**Comment by s4il3sh** [comment]
yes add labels like: group discussion, high priority, check milestone

**Comment by poojashresthacode** [comment]
So editing former labels is counted as a new label or not?

**Comment by LinxuanHu** [comment]
there are several labels already there when we start, does it count to the 10 labels?

**Comment by tirthbha** [comment]
@poojashresthacode I think you need to add new labels.

**Comment by LinxuanHu** [comment]
there were 9 labels, so we need 19 in total?

**Comment by tirthbha** [comment]
Are we allowed to create labels other than the maintainer?

**Comment by LinxuanHu** [comment]
only maintainer can do that

**Comment by tirthbha** [comment]
So only the maintainer will get two points for this, right?

**Comment by LinxuanHu** [comment]
labels and milestones are shared project points, so i think once your group have created enough labels and milestones, every member in the group will get the same points

**Comment by tirthbha** [comment]
Yeah, you are right.

**Comment by Mosaddeq107** [comment]
> So only the maintainer will get two points for this, right?

It's a shared point. So, everyone gets that point, including the maintainer.
